# Generated by Django 2.0.6 on 2019-10-11 15:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import interface.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='文件名称')),
                ('document', models.FileField(default='', storage=interface.storage.OverwriteStorage(), upload_to='documents', verbose_name='文件')),
                ('version', models.CharField(default='1.0.0', max_length=50, verbose_name='版本号')),
                ('updated', models.BooleanField(default=True, verbose_name='全局可更新文件')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_documents', to='equipments.DocumentTag', verbose_name='文件类型')),
            ],
            options={
                'verbose_name': '文件管理',
                'verbose_name_plural': '文件管理',
                'db_table': 'document_download',
            },
        ),
        migrations.CreateModel(
            name='LogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=200, verbose_name='日志内容')),
                ('join_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '日志信息',
                'verbose_name_plural': '日志信息',
                'db_table': 'document_log',
            },
        ),
    ]
