# Generated by Django 2.0.6 on 2019-10-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_singleequipmentdownload_dovument_id'),
        ('interface', '0002_documentdownload_add_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentdownload',
            unique_together={('tag', 'filename')},
        ),
    ]
