# Generated by Django 2.0.6 on 2019-10-11 15:53

from django.db import migrations, models
import django.db.models.deletion
import interface.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='类型')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
                'db_table': 'document_tag',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=100, verbose_name='设备ID')),
                ('updated', models.BooleanField(default=True, verbose_name='是否可更新设备')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_equipments', to='equipments.DocumentTag', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='SingleEquipmentDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='文件名称')),
                ('document', models.FileField(default='', storage=interface.storage.OverwriteStorage(), upload_to='documents', verbose_name='文件')),
                ('version', models.CharField(default='1.0.0', max_length=50, verbose_name='版本号')),
                ('equip_updated', models.BooleanField(default=True, verbose_name='根据设备可更新')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_equipment_documents', to='equipments.Equipment', verbose_name='设备ID')),
            ],
            options={
                'verbose_name': '单设备信息',
                'verbose_name_plural': '单设备信息',
                'db_table': 'single_document_download',
            },
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('tag', 'equipment_id')},
        ),
    ]
