# Generated by Django 2.0.6 on 2019-10-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_singleequipmentdownload_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleequipmentdownload',
            name='dovument_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文件ID'),
        ),
    ]
