# Generated by Django 2.0.6 on 2019-10-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_singleequipmentdownload_dovument_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleequipmentdownload',
            old_name='dovument_id',
            new_name='document_id',
        ),
    ]
