# Generated by Django 2.0.6 on 2019-12-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_auto_20191015_1730'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='singleequipmentdownload',
            unique_together={('equipment', 'document_id')},
        ),
    ]
